### ISSUE TITLE
[dev] UC_ERR_WRITE_UNMAPPED when loading 32bits msvcrt.dll on the demo binary

### ISSUE THREAD

**Issue by Ektoplasma** [qilingframework/qiling#558] opened 2020-10-22 11:31 UTC
Hello,

**The bug**
This issue targets the latest dev version. I just installed Qiling (dev branch) to start playing with it. I tried to emulate the demo binary x86_hello.exe, after collecting the DLLs and registries, but the Unicorn _error Invalid memory write (UC_ERR_WRITE_UNMAPPED)_ is raised. I guess it happens when loading msvcrt.dll.

```
$ qltool run -f ~/qiling/examples/rootfs/x86_windows/bin/x86_hello.exe  --rootfs ~/qiling/examples/rootfs/x86_windows
[+] Initiate stack address at 0xfffdd000
[+] Loading /home/xxx/qiling/examples/rootfs/x86_windows/bin/x86_hello.exe to 0x400000
[+] PE entry point at 0x401280
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/ntoskrnl.exe to 0x10000000
[+] Done with loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/ntoskrnl.exe
[+] Loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/ntdll.dll to 0x10ab7000
[+] Done with loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/ntdll.dll
[+] Loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll to 0x10c51000
[+] Done with loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll
[+] Loading /home/xxx/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/msvcrt.dll to 0x10d26000
Traceback (most recent call last):
  File "/home/xxx/.local/bin/qltool", line 234, in <module>
    ql = Qiling(filename=[options.filename] + options.args, rootfs=options.rootfs, profile=options.profile, output=options.output, console=options.console, log_dir=options.log_dir, env=env)
  File "/home/xxx/.local/lib/python3.8/site-packages/qiling/core.py", line 164, in __init__
    self.loader.run()
  File "/home/xxx/.local/lib/python3.8/site-packages/qiling/loader/pe.py", line 398, in run
    self.load()
  File "/home/xxx/.local/lib/python3.8/site-packages/qiling/loader/pe.py", line 525, in load
    super().load_dll(entry.dll, self.is_driver)
  File "/home/xxx/.local/lib/python3.8/site-packages/qiling/loader/pe.py", line 86, in load_dll
    cmdline_entry = self.set_cmdline(entry.name, entry.address, data)
  File "/home/xxx/.local/lib/python3.8/site-packages/qiling/loader/pe.py", line 133, in set_cmdline
    self.ql.mem.write(addr, str(self.cmdline).encode("utf-16le"))
  File "/home/xxx/.local/lib/python3.8/site-packages/qiling/os/memory.py", line 186, in write
    return self.ql.uc.mem_write(addr, data)
  File "/home/xxx/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 443, in mem_write
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

Then I installed the stable latest release and everything is fine.

**Sample Code**
`$ qltool run -f ~/qiling/examples/rootfs/x86_windows/bin/x86_hello.exe  --rootfs ~/qiling/examples/rootfs/x86_windows`

**Expected behavior**
The Stable version (1.1.3) runs fine 
```
[... Setup up context and Loading DLLs...]

__set_app_type()
SetUnhandledExceptionFilter(lpTopLevelExceptionFilter = 0x401110) = 0x0
__getmainargs(_Argc = 0x405004, _Argv = 0x405000, _Env = 0xffffcfcc, _DoWildCard = 0xffffffff, _StartInfo = 0xffffcfd0) = 0x0
__p__fmode() = 0x50354f8
atexit(func = 0x401340) = 0x0
atexit(func = 0x401880) = 0x0
__p__environ() = 0x50354fc
Hello world!
puts(str = "Hello world!") = 0xd
_cexit()
ExitProcess(uExitCode = 0x0)
```

**Comment by xwings** [comment] 2020-10-25 05:50
I am on dev and it seems to be working fine.

this exe is being tested by CI for dev and stable. Should not have any issue

**Comment by elicn** [comment] 2021-06-29 12:42
Confirmed to work on v1.24 without any problem.
@xwings I guess you can close it.

**Closed** 2022-04-24 10:25 UTC
