### ISSUE TITLE
glibc

### ISSUE THREAD

**Issue by LoverOfSadness** [qilingframework/qiling#1234] opened 2022-09-25 12:44 UTC
glibc 2.36

**Comment by xwings** [comment] 2022-09-26 11:34
any more information?

**Comment by LoverOfSadness** [comment] 2022-09-26 16:09
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found

**Comment by elicn** [comment] 2022-09-29 08:50
Duplicate of #1201

**Closed by elicn** 2022-09-29 08:50 UTC
