### ISSUE TITLE
An unimplemented SYSCALL(__NR_rseq) in GLIBC_2.34 triggered an exception

### ISSUE THREAD

**Issue by yikesoftware** [qilingframework/qiling#1242] opened 2022-10-10 14:41 UTC
I compiled a dynamically linked program under ubuntu22.04, but used a syscall that was not implemented for the time being in the program initialization phase, which caused the program to fail to start normally.

Error Info:

```shell
...
[!] 	0x7ffff7dea1cf: syscall ql_syscall_rseq number = 0x14e(334) not implemented
/lib/x86_64-linux-gnu/libc.so.6: CPU ISA level is lower than required
...
[=] 	writev(fd = 0x2, vec = 0x80000000d510, vlen = 0x2) = 0x46
[=] 	exit_group(code = 0x7f) = ?
...
Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

**Comment by yikesoftware** [comment] 2022-10-10 20:22
I found a temporary solution, which is to skip this error through hook.

hook code:

```python3
...
def by_pass_isa_check(ql: Qiling) -> None:
    print("by_pass_isa_check():")
    ql.arch.regs.rip += 0x15
    pass
...
ld_so_base = 0x7ffff7dd5000
ql.hook_address(by_pass_isa_check, ld_so_base+0x2389f) # ld.so base + jz offset
```

Source:

![image](https://user-images.githubusercontent.com/40513718/194943267-99f24506-0712-45b8-a9c0-22f7e4eebdf8.png)


IDA Disassembly:

![image](https://user-images.githubusercontent.com/40513718/194943166-6c6d094d-6ff0-4f31-b093-9531c8cf8c94.png)

**Comment by elicn** [comment] 2022-10-12 01:11
Duplicate of #1201

**Closed by elicn** 2022-10-12 01:11 UTC
