### ISSUE TITLE
IDA Plugin crashes with "'NoneType' object has no attribute 'fileno'" after calling "Setup"

### ISSUE THREAD

**Issue by OevreFlataeker** [qilingframework/qiling#475] opened 2020-08-24 15:26 UTC
Using the current qiling master branch and the IDA Pro plugin with IDA 7.5 on Windows 10 64 bit with Python 3.8 x64.
Plugin installs correctly. When running "Setup" from the Qiling context menu and choosing a root folder, no matter what I chose, the dialog is finished with

```
---------------------------------------------------------------------------------------------
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
Qiling Emulator Plugin For IDA, by Qiling Team. Version 1.1.1, 2020
Based on Qiling v1.1.1
Find more information about Qiling at https://qiling.io
---------------------------------------------------------------------------------------
Set rootfs success
Qiling initialized done
Traceback (most recent call last):
  File "C:/Users/xxx/qiling/qiling/extensions/idaplugin/Qiling.py", line 408, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "C:/Users/xxx/qiling/qiling/extensions/idaplugin/Qiling.py", line 942, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Users/xxx/qiling/qiling/extensions/idaplugin/Qiling.py", line 942, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Users/xxx/qiling/qiling/extensions/idaplugin/Qiling.py", line 618, in ql_start
    self.qlemu.start()
  File "C:/Users/xxx/qiling/qiling/extensions/idaplugin/Qiling.py", line 498, in start
    qlstdin = QlEmuMisc.QLStdIO('stdin', sys.__stdin__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'
```

Using an ordinary interactive python 3.8 shell of course prints a proper value for fileno():

```
C:\Users\xxx>c:\python38\python -c "import sys; print(sys.__stdin__.fileno())"
0
```

**Comment by OevreFlataeker** [comment] 2020-08-24 17:09
For you reference the problem is clearly reproducible in the IDA command line console in IDA itself:

```python
Python>if sys.__stdin__ is None: print("__stdin__ is none!")
__stdin__ is none!
Python>sys.__stdin__.fileno()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'fileno'
```

**Comment by xwings** [comment] 2020-08-25 02:34
fix by @kabeor 

https://github.com/qilingframework/qiling/pull/476

**Comment by kabeor** [comment] 2020-08-25 02:46
This issue have been fixed now. But strongly recommended to use under linux or mac, windows always has some strange thing :)

**Closed** 2020-08-26 09:56 UTC

**Comment by OevreFlataeker** [comment] 2020-08-26 21:27
Thanks will test it! Unfortunately I only have a Windows IDA license and cannot run it on Linux :-( (Think the freeware version does not support plugins? Does it?)

**Comment by kabeor** [comment] 2020-08-27 04:16
yes, and IDA freeware version is too low to support python3

**Comment by trib0r3** [comment] 2020-09-15 09:23
The issue is back once again:

```
Register actions.
Set rootfs success
Qiling initialized done
Traceback (most recent call last):
  File "//vmware-host/qiling/qiling/extensions/idaplugin/qilingida.py", line 765, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "//vmware-host/qiling/qiling/extensions/idaplugin/qilingida.py", line 1554, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "//vmware-host/qiling/qiling/extensions/idaplugin/qilingida.py", line 1554, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "//vmware-host/qiling/qiling/extensions/idaplugin/qilingida.py", line 987, in ql_start
    self.qlemu.start()
  File "//vmware-host/qiling/qiling/extensions/idaplugin/qilingida.py", line 862, in start
    self.ql = Qiling(filename=[self.path], rootfs=self.rootfs, output="debug")
  File "C:\Program Files\Python37\lib\site-packages\qiling\core.py", line 175, in __init__
    self.os = self.os_setup()
  File "C:\Program Files\Python37\lib\site-packages\qiling\core_utils.py", line 145, in os_setup
    return ql_get_module_function(module_name, function_name)(self)
  File "C:\Program Files\Python37\lib\site-packages\qiling\os\windows\windows.py", line 21, in __init__
    QlOs.__init__(self, ql)
  File "C:\Program Files\Python37\lib\site-packages\qiling\os\os.py", line 19, in __init__
    self.stdin = ql_file('stdin', sys.stdin.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'
```

**Comment by kabeor** [comment] 2020-09-15 09:52
@trib0r3 Can you please provide more info like your qiling's version, commit hash etc. ? Will help me to find reason quickly.

**Comment by trib0r3** [comment] 2020-09-16 08:02
@kabeor e9df4410c59416310cb57ddfeea1412ae1e0aee1

**Comment by kabeor** [comment] 2020-09-16 10:56
@trib0r3  Please try update to the latest version of the dev branch. And make sure your IDA version >= 7.4.
This doc maybe helpful:  https://docs.qiling.io/en/latest/ida/
