### ISSUE TITLE
syscall number = 0x4e(78) not implement

### ISSUE THREAD

**Issue by bannsec** [qilingframework/qiling#165] opened 2020-03-20 18:26 UTC
When attempting to use qiling to run `/bin/ls` on my default bionic install, i get a notice that syscall 78 is not implemented, then qiling immediately hangs until i manually kill it.

**Comment by xwings** [comment] 2020-03-21 00:37
Hi,

This is not a bug, this is due to the /bin/ls needs a syscall which not yet implemented by us.

for example, syscall 78 or 0x4e in X86_64 should be pointing to getdent , according to https://syscalls.w3challs.com/?arch=x86_64

would you be abe to do a Pull Request ?

**Comment by xwings** [comment] 2020-03-23 22:01
Thanks @ucgJhe !
I will close this issue for now

**Closed** 2020-03-23 22:01 UTC
