### ISSUE TITLE
GetProcAddress() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by QWERTYz12** [qilingframework/qiling#848] opened 2021-07-03 15:26 UTC
Hey, 
I am trying to create a python script to hook the API GetProcAddress so that I am able to see the dynamic imports of a file. For this example, I am using emotet malware. (MD5 hash: B2EA9495D718E0F672D4B274D6DF7C07)

This is my script:
```
import sys
import pefile
from qiling import *
from qiling.const import *
from capstone import *

def loader_pe(pe):
    entry_point = pe.OPTIONAL_HEADER.AddressOfEntryPoint
    data = pe.get_memory_mapped_image()[entry_point:]
    cs = Cs(CS_ARCH_X86, CS_MODE_32)
    cs.detail = True
    global rdbin
    rdbin = cs.disasm(data, 0x10000)
    return rdbin

def check_arch(pe):
    if pe.FILE_HEADER.Machine == 0x14c:
        bit = 32
    elif pe.FILE_HEADER.Machine == 0x8664:
        bit = 64
    print("[+] Sample is %s bit" % bit)
    return bit

def GetProcAddress(ql, addr, params): 
    print(params)
    return addr, params

def stop(ql):
    print("[+] Address found")
    ql.emu_stop()

def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs)  
    ql.hook_address(stop, 0x0042B726)
    ql.set_api("GetProcAddress", GetProcAddress, QL_INTERCEPT.EXIT)
    ql.run()

file = sys.argv[-1]
if __name__ == "__main__":
    exefile = sys.argv[-1]
    try:
        exe = pefile.PE(exefile)
    except OSError as e:
        print(e)
        sys.exit()
    except pefile.PEFormatError as e:
        sys.exit()
    rdbin = loader_pe(exe)
    check_arch(exe)
    my_sandbox([exefile], "examples/rootfs/x86_windows")
```
This is the error I am facing:
```
[+] Sample is 32 bit
[=]     Initiate stack address at 0xfffdd000
[=]     Loading .\emotet.exe to 0x400000
[=]     PE entry point at 0x41fef1
[=]     TEB addr is 0x6000
[=]     PEB addr is 0x6044
[=]     Loading examples/rootfs/x86_windows\Windows\System32\ntdll.dll to 0x10000000
[!]     Warnings while loading examples/rootfs/x86_windows\Windows\System32\ntdll.dll:
[!]      - SizeOfHeaders is smaller than AddressOfEntryPoint: this file cannot run under Windows 8.
[!]      - AddressOfEntryPoint lies outside the sections' boundaries. AddressOfEntryPoint: 0x0
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\ntdll.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\kernel32.dll to 0x10175000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\kernel32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\user32.dll to 0x10280000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\user32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\gdi32.dll to 0x10374000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\gdi32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\comdlg32.dll to 0x103f6000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\comdlg32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\winspool.drv to 0x10471000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\winspool.drv
[=]     Loading examples/rootfs/x86_windows\Windows\System32\advapi32.dll to 0x104c2000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\advapi32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\comctl32.dll to 0x10562000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\comctl32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\shlwapi.dll to 0x105e6000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\shlwapi.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\oledlg.dll to 0x1063d000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\oledlg.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\ole32.dll to 0x10659000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\ole32.dll
[=]     Loading examples/rootfs/x86_windows\Windows\System32\oleaut32.dll to 0x107b5000
[=]     Done with loading examples/rootfs/x86_windows\Windows\System32\oleaut32.dll
[=]     GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xffffcff0)
[=]     GetCurrentProcessId() = 0x7cc
[=]     GetCurrentThreadId() = 0x0
[=]     GetTickCount() = 0x30d40
[=]     QueryPerformanceCounter(lpPerformanceCount = 0xffffcfe8) = 0x0
[=]     GetStartupInfoA(lpStartupInfo = 0xffffcf94) = 0x0
[=]     HeapCreate(flOptions = 0, dwInitialSize = 0x1000, dwMaximumSize = 0) = 0x5000b8c
[=]     GetModuleHandleW(lpModuleName = "KERNEL32.DLL") = 0x10175000
[x]     GetProcAddress() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\windows\windows.py", line 135, in hook_winapi
    api_func(ql, address, api_name)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\windows\fncc.py", line 162, in wrapper
    return ql.os.call(pc, func, params, onenter, onexit, passthru=passthru)
  File "C:\Users\user\Desktop\xxx\xxx\lib\site-packages\qiling\os\os.py", line 133, in call
    targs, retval, retaddr = self.fcall.call(func, proto, args, onenter, onexit, passthru)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\fcall.py", line 148, in call
    override = hook_onexit(ql, pc, params, retval)
TypeError: GetProcAddress() takes 3 positional arguments but 4 were given

Traceback (most recent call last):
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\windows\windows.py", line 135, in hook_winapi
    api_func(ql, address, api_name)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\windows\fncc.py", line 162, in wrapper
    return ql.os.call(pc, func, params, onenter, onexit, passthru=passthru)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\os.py", line 133, in call
    targs, retval, retaddr = self.fcall.call(func, proto, args, onenter, onexit, passthru)
  File "C:\Users\user\Desktop\xxxb\site-packages\qiling\os\fcall.py", line 148, in call
    override = hook_onexit(ql, pc, params, retval)
TypeError: GetProcAddress() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\github_qiling.py", line 55, in <module>
    my_sandbox([exefile], "examples/rootfs/x86_windows")
  File ".\github_qiling.py", line 40, in my_sandbox
    ql.run()
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\core.py", line 755, in run
    self.os.run()
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\windows\windows.py", line 188, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.exit_point, self.ql.timeout, self.ql.count)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\core.py", line 899, in emu_start
    raise self._internal_exception
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\utils.py", line 158, in wrapper
    return func(*args, **kw)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\core_hooks.py", line 111, in _hook_trace_cb
    ret = h.call(ql, addr, size)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\core_hooks_types.py", line 23, in call
    return self.callback(ql, *args)
  File "C:\Users\user\Desktop\xxx\lib\site-packages\qiling\os\windows\windows.py", line 140, in hook_winapi
    raise QlErrorSyscallError("Windows API Implementation Error")
qiling.exception.QlErrorSyscallError: Windows API Implementation Error
```
Thanks for any help! :)

**Comment by elicn** [comment] 2021-07-04 12:42
When hooking on-exit (that is, using the `QL_INTERCEPT.EXIT` value) there is an additional argument passed to the hook which holds the return value obtained after the function was called. The on-exit hook may inspect and use it if it needs to:
```python3
def GetProcAddress(ql: Qiling, addr: int, params, retval: int):
    # do things here ...
```
The return value of the on-exit hook, however, has inconsistent meaning across different OS.
On Windows, Linux, MacOS and UEFI the on-exit hook may return an alternate return value (i.e. overriding the original return value of the hooked function with another one). If nothing is returned, the return value remains unchanged.

In general:
- On-entry hooks may modify the _arguments_ and the _source address_ before the function is called
- On-exit hooks may modify the _return value_ after the function was called

**Comment by QWERTYz12** [comment] 2021-07-04 16:08
Hey thanks for the reply! Im trying it on a Windows OS but I still get errors. 
I tried to parse the additional argument retval into the GetProcAddress function: 
```
def GetProcAddress(ql, addr, params, retval): 
    print(params)
    return addr, params 
```
but i get the error:
```
[x]     an integer is required (got type tuple)
```

I also tried printing out the retval which shows me "270049019" and tried to parse this integer into the function via:
```
def GetProcAddress(ql, addr, params, retval= 270049019): 
    print(params)
    print (retval)
    return addr, params 
```
but I get the same error as above. 

Thanks for any help! :)

**Comment by elicn** [comment] 2021-07-04 18:15
It's because your hook returns a tuple instead of an integer (an alternate function return value). As I wrote earlier, your hook should return either an integer or nothing at all.

**Comment by QWERTYz12** [comment] 2021-07-06 06:31
Got it already! Thanks for the help!! 👍

**Comment by elicn** [comment] 2021-07-06 14:05
@QWERTYz12 Glad it helped. If the issue is resolved, please close it.

**Closed** 2021-07-07 06:35 UTC
