### ISSUE TITLE
fail to load dynamic library

### ISSUE THREAD

**Issue by baptistapedro** [qilingframework/qiling#99] opened 2020-02-17 23:12 UTC
```
lamba@ubuntu:~/qiling$ sudo pip3 install keystone-engine
The directory '/home/lamba/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/lamba/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: keystone-engine in /usr/local/lib/python3.6/dist-packages
lamba@ubuntu:~/qiling$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiling import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lamba/qiling/qiling/__init__.py", line 1, in <module>
    from .core import *
  File "/home/lamba/qiling/qiling/core.py", line 13, in <module>
    from qiling.os.utils import *
  File "/home/lamba/qiling/qiling/os/utils.py", line 22, in <module>
    from keystone import *
  File "/usr/local/lib/python3.6/dist-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/usr/local/lib/python3.6/dist-packages/keystone/keystone.py", line 74, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

```

**Comment by chfl4gs** [comment] 2020-02-18 03:29
Duplicate of #18 . See workaround in reply.

**Closed by chfl4gs** 2020-02-18 03:29 UTC
